import { RestaurantType } from 'src/types';

import BirayniByKiloImg from 'src/images/restaurants/delivery/biryani-by-kilo.png';
import WowMomoImg from 'src/images/restaurants/delivery/wow-momo.png';
import BalleBalleDhabaImg from 'src/images/restaurants/delivery/balle-balle-dhaba.png';
import DominosPizzaImg from 'src/images/restaurants/delivery/dominos-pizza.png';
import FabelleChocolatesImg from 'src/images/restaurants/delivery/fabelle-chocolates-itc-sonar.png';
import KFCImg from 'src/images/restaurants/delivery/kfc.png';
import Oudh1590Img from 'src/images/restaurants/delivery/oudh-1590.png';
import MonginisImg from 'src/images/restaurants/delivery/monginis.png';
import BurgerKingImg from 'src/images/restaurants/delivery/burger-king.png';
import MomoIAmImg from 'src/images/restaurants/delivery/momo-i-am.png';
import StarbucksCoffeeImg from 'src/images/restaurants/delivery/starbucks-coffee.png';
import BaskinRobinsImg from 'src/images/restaurants/delivery/baskin-robins.png';

const restaurants: RestaurantType = {
  Delivery: [
    {
      id: 'Delivery_1',
      title: 'Biryani By Kilo',
      subtitle: 'Biryani, Mughlai, Kebab, Hyderabadi',
      imagePath: BirayniByKiloImg,
      rating: 4.1,
      price: '400 for one',
      timeToDeliver: '90 mins',
      discount: '50% OFF',
      numOfRecentOrder: 2400,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_2',
      title: 'WOW! Momo',
      subtitle: 'Momos, Fast Food, Tibetan',
      imagePath: WowMomoImg,
      rating: 4.0,
      price: '400 for one',
      timeToDeliver: '26 mins',
      discount: '50% OFF',
      numOfRecentOrder: 975,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_3',
      title: 'Balle Balle Dhaba',
      subtitle: 'North Indian, Mughlai, Kebab',
      imagePath: BalleBalleDhabaImg,
      rating: 3.9,
      price: '400 for one',
      timeToDeliver: '29 mins',
      discount: '40% OFF',
      proDiscount: 'Pro extra 15% OFF',
      isPromoted: true,
      numOfRecentOrder: 3225,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_4',
      title: "Domino's Pizza",
      subtitle: 'Pizza, Fast Food, Beverages, Desserts',
      imagePath: DominosPizzaImg,
      rating: 4.4,
      price: '400 for one',
      timeToDeliver: '30 mins',
      discount: '30% OFF',
      numOfRecentOrder: 3800,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_5',
      title: 'Fabelle Chocolates - ITC Sonar',
      subtitle: 'Desserts, Bakery',
      imagePath: FabelleChocolatesImg,
      rating: 4.5,
      price: '400 for one',
      timeToDeliver: '35 mins',
      discount: '50% OFF',
      numOfRecentOrder: 900,
      isPromoted: true,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_6',
      title: 'KFC',
      subtitle: 'Burger, Fast Food, Biryani, Desserts, Beverages',
      imagePath: KFCImg,
      rating: 4.5,
      price: '400 for one',
      timeToDeliver: '35 mins',
      numOfRecentOrder: 4200,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_7',
      title: 'Oudh 1590',
      subtitle: 'Biryani, Kebab, Awadhi, Mughlai',
      imagePath: Oudh1590Img,
      rating: 4.2,
      price: '400 for one',
      timeToDeliver: '31 mins',
      discount: '50% OFF',
      numOfRecentOrder: 6300,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_8',
      title: 'Monginis',
      subtitle: 'Bakery, Desserts, Fast Food',
      imagePath: MonginisImg,
      rating: 3.6,
      price: '100 for one',
      timeToDeliver: '21 mins',
      discount: 'Flat 10% OFF',
      numOfRecentOrder: 725,
      isSafeDelivery: true,
    },
    {
      id: 'Delivery_9',
      title: 'Burger King',
      subtitle: 'Burger, Fast Food, Beverages',
      imagePath: BurgerKingImg,
      rating: 3.8,
      price: '100 for one',
      timeToDeliver: '45 mins',
      numOfRecentOrder: 7400,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_10',
      title: 'Momo I Am',
      subtitle: 'Finger Food, Momos, Tibetan, Asian, Chinese',
      imagePath: MomoIAmImg,
      rating: 4.2,
      price: '100 for one',
      timeToDeliver: '39 mins',
      discount: '30% OFF',
      numOfRecentOrder: 1725,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_11',
      title: 'Starbucks Coffee',
      subtitle: 'Cafe, Beverages, Fast Food, Desserts',
      imagePath: StarbucksCoffeeImg,
      rating: 4.3,
      price: '150 for one',
      timeToDeliver: '36 mins',
      discount: '50% OFF',
      proDiscount: 'Pro extra 15% OFF',
      isPromoted: true,
      numOfRecentOrder: 700,
      isMaxSafetyDelivery: true,
    },
    {
      id: 'Delivery_12',
      title: 'Baskin Robins',
      subtitle: 'Ice Cream, Desserts, Beverages, Shake',
      imagePath: BaskinRobinsImg,
      rating: 4.2,
      price: '50 for one',
      timeToDeliver: '16 mins',
      discount: '20% OFF',
      numOfRecentOrder: 550,
      isMaxSafetyDelivery: true,
    },
  ],
  'Dine-Out': [],
  Nightlife: [],
};

export default restaurants;
